bots/bots/urls.py
# -*- coding: utf-8 -*-
"""
Bots urls
"""

from django.contrib import admin
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import views as auth_views
from django.urls import include, re_path

from . import botsglobal
from . import views
from . import healthcheck


staff_required = user_passes_test(lambda u: u.is_staff)
superuser_required = user_passes_test(lambda u: u.is_superuser)
run_permission = user_passes_test(lambda u: u.has_perm('bots.change_mutex'))


# Bots URL patterns
bots_paths = [
    # Health checks (no auth required - for K8s probes)
    re_path(r'^health/live/?$', healthcheck.health_live, name='health_live'),
    re_path(r'^health/ready/?$', healthcheck.health_ready, name='health_ready'),
    re_path(r'^health/startup/?$', healthcheck.health_startup, name='health_startup'),
    re_path(r'^health/ping/?$', healthcheck.health_ping, name='health_ping'),
    # Main views - login required
    re_path(r'^home.*', login_required(views.home), name='home'),
    re_path(r'^incoming.*', login_required(views.incoming), name='incoming'),
    re_path(r'^outgoing.*', login_required(views.outgoing), name='outgoing'),
    re_path(r'^detail.*', login_required(views.detail), name='detail'),
    re_path(r'^process.*', login_required(views.process), name='process'),
    re_path(r'^document.*', login_required(views.document), name='document'),
    re_path(r'^reports.*', login_required(views.reports), name='reports'),
    re_path(r'^confirm.*', login_required(views.confirm), name='confirm'),
    re_path(r'^filer.*', login_required(views.filer), name='filer'),
    re_path(r'^srcfiler.*', login_required(views.srcfiler), name='srcfiler'),
    re_path(r'^logfiler.*', login_required(views.logfiler), name='logfiler'),
    # only staff
    re_path(r'^runengine.+', run_permission(views.runengine), name='runengine'),
    # only superuser
    re_path(r'^delete.*', superuser_required(views.delete), name='delete'),
    re_path(r'^plugin/index.*', superuser_required(views.plugin_index), name='plugin_index'),
    re_path(r'^plugin.*', superuser_required(views.plugin), name='plugin'),
    re_path(r'^plugout/index.*', superuser_required(views.plugout_index), name='plugout_index'),
    re_path(r'^plugout/backup.*', superuser_required(views.plugout_backup), name='plugout_backup'),
    re_path(r'^plugout.*', superuser_required(views.plugout), name='plugout'),
    re_path(r'^sendtestmail.*', superuser_required(views.sendtestmailmanagers), name='sendtestmail'),
    # catch-all
    re_path(r'^.*', views.index),
]

auth_paths = [
    # Auth
    re_path(
        r"^login.*", auth_views.LoginView.as_view(template_name="admin/login.html"),
        name="login",
    ),
    re_path(
        r"^logout.*", auth_views.LogoutView.as_view(next_page="/"),
        name="logout",
    ),
]
if botsglobal.ini.getboolean("webserver", "menu_changepassword", True):
    auth_paths += [
        re_path(
            r"^password_change/$", auth_views.PasswordChangeView.as_view(),
            name="password_change",
        ),
        re_path(
            r"^password_change/done/$", auth_views.PasswordChangeDoneView.as_view(),
            name="password_change_done",
        ),
    ]


urlpatterns = auth_paths + [
    # only staff
    # do not show django admin root page
    # re_path(r'^admin/$', login_required(views.home)),
    # do not show django admin root page
    # re_path(r'^admin/bots/$', login_required(views.home)),
    re_path(r'^admin/', admin.site.urls),
    # Bots urls
    re_path('bots/', include((bots_paths, 'bots'), namespace='bots')),
    re_path(r'^.*', views.index),
]

# pylint: disable=invalid-name
handler500 = 'bots.views.server_error'

bots/bots/templates/bots/nav/admin_auth.html
{% include 'bots/nav/admin_auth_user.html' %}
{% include 'bots/nav/admin_auth_group.html' %}

bots/bots/templates/bots/nav/admin_auth_group.html
{% if perms.auth.view_group or perms.change_group %}{% load i18n %}
<li><a href="{% url 'admin:auth_group_changelist' %}" class="ico-group">{% trans 'UserGroups' %}</a>
{% if perms.auth.add_group %}<ul>
  <li><a href="{% url 'admin:auth_group_add' %}" class="ico-add">{% trans 'Add' %}</a></li>
</ul>{% endif %}
</li>{% endif %}

bots/bots/templates/bots/nav/admin_auth_user.html
{% if perms.auth.view_user or perms.auth.change_user %}{% load i18n %}
<li><a href="{% url 'admin:auth_user_changelist' %}" class="ico-user">{% trans 'Users' %}</a>
<ul>
  <li><a href="{% url 'admin:auth_user_changelist' %}?is_staff__exact=1">{% trans 'Staff' %}</a></li>
  <li><a href="{% url 'admin:auth_user_changelist' %}?is_superuser__exact=1">{% trans 'Superuser' %}</a></li>
  <li><a href="{% url 'admin:auth_user_changelist' %}?is_active__exact=1" class="ico-yes">{% trans 'Actives' %}</a></li>
  <li><a href="{% url 'admin:auth_user_changelist' %}?is_active__exact=0" class="ico-no">{% trans 'Inactives' %}</a></li>
  {% if perms.auth.add_user %}<li><a href="{% url 'admin:auth_user_add' %}" class="ico-add">{% trans 'Add' %}</a></li>{% endif %}
</ul>
</li>{% endif %}

bots/bots/templates/bots/nav/allruns.html
{% if perms.bots.view_filereport or perms.change_filereport %}{% load i18n %}
<li>{% if perms.bots.view_report %}<a {% if not bots_touchscreen %}href="{% url 'bots:reports' %}"{% endif %} class="ico-reports after-title" title="{% trans 'All runs' %}"></a>
<ul>
  <li><a href="{% url 'bots:reports' %}/?all" class="ico-reports">{% trans 'Report (per run)' %}{% if not bots_touchscreen %} *{% endif %}</a></li>
  <li><a href="{% url 'bots:reports' %}/?status=1" class="icon-err">{% trans 'Report errors' %}</a></li>
  <li><a href="{% url 'bots:reports' %}/?select" class="ico-search">{% trans 'Select report' %}</a></li>
{% else %}<a>{% trans 'All runs' %}</a>
<ul>{% endif %}
  <li><hr/></li>
  <li><a href="{% url 'bots:confirm' %}" class="ico-confirmrule">{% trans 'Confirmations' %}</a>
  <ul>
    <li><a href="{% url 'bots:confirm' %}?confirmed=1" class="ico-confirmed">{% trans 'Confirmed' %}</a></li>
    <li><a href="{% url 'bots:confirm' %}?confirmed=0" class="ico-unconfirmed">{% trans 'Unconfirmed' %}</a></li>
    <li><a href="{% url 'bots:confirm' %}?confirmidta=-1" class="ico-confirmed">{% trans 'Manual confirm' %}</a></li>
  </li></ul>
  <li><a href="{% url 'bots:confirm' %}?confirmidta=0" class="ico-pending">{% trans 'Pending ...' %}</a></li>
  <li><a href="{% url 'bots:confirm' %}/?select" class="ico-search">{% trans 'Select confirmations' %}</a></li>
{% include 'bots/nav/documents.html' %}
  <li><hr/></li>
  <li><a href="{% url 'bots:process' %}/?all" class="icon-err">{% trans 'Process Errors' %}</a></li>
  <li><a href="{% url 'bots:process' %}/?lastrun=1" class="icon-err">{% trans 'Last process errors' %}</a></li>
  <li><a href="{% url 'bots:process' %}/?select" class="ico-search">{% trans 'Select process errors' %}</a></li>
</ul>
</li>{% endif %}

bots/bots/templates/bots/nav/app.html
{% if perms.bots %}
<li><a href="{% url 'bots:home' %}" class="icon-bots">Bots EDI</a>
  <ul>
    {% include 'bots/nav/index.html' %}
  </ul>
</li>
{% endif %}

bots/bots/templates/bots/nav/config.html
{% if user.is_staff and perms.bots %}{% load i18n %}
<li><a href="{% url 'admin:app_list' 'bots' %}" class="ico-config after-title" title="{% trans 'Configuration' %}"></a>
  <ul>
    {# ROUTES #}{% if perms.bots.view_routes or perms.bots.change_routes %}{% url 'admin:bots_routes_changelist' as url_bots_routes %}
    <li><a href="{{ url_bots_routes }}" class="ico-routes">{% trans 'Routes' %}</a>
      <ul>
        <li><a class="ico-fromchannel">{% trans 'Incoming channel' %}</a>
          <ul>{% for channeltype, channeltype_title in channeltypes %}
            <li title="{{ channeltype_title }}"><a href="{{ url_bots_routes }}?fromchannel__type__exact={{ channeltype }}">{{ channeltype_title }}</a></li>{% endfor %}
          </ul>
        </li>
        <li><a class="ico-tochannel">{% trans 'Outgoing channel' %}</a>
          <ul>{% for channeltype, channeltype_title in channeltypes %}
            <li title="{{ channeltype_title }}"><a href="{{ url_bots_routes }}?tochannel__type__exact={{ channeltype }}">{{ channeltype_title }}</a></li>{% endfor %}
          </ul>
        </li>
        <li><a class=="ico-editype">{% trans 'From editype' %}</a>
          <ul>{% for editype, editype_title in editypes %}
            <li title="{{ editype_title }}"><a href="{{ url_bots_routes }}?fromeditype__exact={{ editype }}">{{ editype_title|truncatechars:22 }}</a></li>{% endfor %}
          </ul>
        </li>
        <li><a href="{{ url_bots_routes }}?notindefaultrun__exact=0">{% trans 'Default run' %}</a>
          <ul>
            <li><a href="{{ url_bots_routes }}?notindefaultrun__exact=0&active__exact=1" class="ico-yes">{% trans 'Actives' %}</a></li>
            <li><a href="{{ url_bots_routes }}?notindefaultrun__exact=0&active__exact=0"class="ico-no">{% trans 'Inactives' %}</a></li>
            <li><hr/></li>
            <li><a href="{{ url_bots_routes }}?notindefaultrun__exact=1">{% trans 'Not in default run' %}</a></li>
            <li><a href="{{ url_bots_routes }}?notindefaultrun__exact=1&active__exact=1" class="ico-yes">{% trans 'Actives' %}</a></li>
            <li><a href="{{ url_bots_routes }}?notindefaultrun__exact=1&active__exact=0"class="ico-no">{% trans 'Inactives' %}</a></li>
          </ul>
        </li>
        <li><a href="{{ url_bots_routes }}?dirmonitor__exact=1" class="ico-dirmonitor">{% trans 'Dirmonitor' %}</a>
          <ul>
            <li><a href="{{ url_bots_routes }}?dirmonitor__exact=1&active__exact=1" class="ico-yes">{% trans 'Actives' %}</a></li>
            <li><a href="{{ url_bots_routes }}?dirmonitor__exact=1&active__exact=0"class="ico-no">{% trans 'Inactives' %}</a></li>
          </ul>
        </li>
        <li><a href="{{ url_bots_routes }}?active__exact=1" class="ico-yes">{% trans 'Actives' %}</a></li>
        <li><a href="{{ url_bots_routes }}?active__exact=0"class="ico-no">{% trans 'Inactives' %}</a></li>
        {% if perms.bots.add_routes %}<li><a href="{% url 'admin:bots_routes_add' %}" class="ico-add">{% trans 'Add' %}</a></li>{% endif %}
      </ul>
    </li>{% endif %}

    {# CHANNELS #}{% if perms.bots.view_channel or perms.bots.change_channel %}{% url 'admin:bots_channel_changelist' as url_bots_channel %}
    <li><a href="{{ url_bots_channel }}" class="ico-channel">{% trans 'Channels' %}</a>
      <ul>
        <li><a href="{{ url_bots_channel }}?inorout__exact=in" class="ico-fromchannel">{% trans 'in'|title %}</a>
          <ul>{% if perms.bots.add_channel %}<li><a href="{% url 'admin:bots_channel_add' %}?inorout=in" class="ico-add">{% trans 'Add' %} {% trans 'incoming channel' %}</a></li>{% endif %}{% for channeltype, channeltype_title in channeltypes %}
            <li title="{{ channeltype_title }}"><a href="{{ url_bots_channel }}?inorout__exact=in&type__exact={{ channeltype }}" >{{ channeltype_title }}</a></li>{% endfor %}
          </ul>
        </li>
        <li><a href="{{ url_bots_channel }}?inorout__exact=out" class="ico-tochannel">{% trans 'out'|title %}</a>
          <ul>{% if perms.bots.add_channel %}<li><a href="{% url 'admin:bots_channel_add' %}?inorout=out" class="ico-add">{% trans 'Add' %} {% trans 'outgoing channel' %}</a></li>{% endif %}{% for channeltype, channeltype_title in channeltypes %}
            <li title="{{ channeltype_title }}"><a href="{{ url_bots_channel }}?inorout__exact=out&type__exact={{ channeltype }}">{{ channeltype_title }}</a></li>{% endfor %}
          </ul>
        </li>
        <li><a>{% trans 'Type' %}</a>
          <ul>{% for channeltype, channeltype_title in channeltypes %}
            <li title="{{ channeltype_title }}"><a href="{{ url_bots_channel }}?type__exact={{ channeltype }}">{{ channeltype_title }}</a></li>{% endfor %}
          </ul>
        </li>
        {% if perms.bots.add_channel %}<li><a href="{% url 'admin:bots_channel_add' %}" class="ico-add">{% trans 'Add' %}</a></li>{% endif %}
      </ul>
    </li>{% endif %}

    {# TRANSLATE #}{% if perms.bots.view_translate or perms.bots.change_translate %}{% url 'admin:bots_translate_changelist' as url_bots_translate %}
    <li><a href="{{ url_bots_translate }}" class="ico-translate">{% trans 'Translations' %}</a>
      <ul>
        <li><a href="{{ url_bots_translate }}?o=2" class="ico-in">{% trans 'Incoming' %}</a>
          <ul>{% for editype, editype_title in editypes %}
            <li title="{{ editype_title }}"><a href="{{ url_bots_translate }}?fromeditype__exact={{ editype }}">{{ editype_title|truncatechars:22 }}</a></li>{% endfor %}
          </ul>
        </li>
        <li><a href="{{ url_bots_translate }}?o=8" class="ico-out">{% trans 'Outgoing' %}</a>
          <ul>{% for editype, editype_title in editypes %}
            <li title="{{ editype_title }}"><a href="{{ url_bots_translate }}?toeditype__exact={{ editype }}">{{ editype_title|truncatechars:22 }}</a></li>{% endfor %}
          </ul>
        </li>
        <li><a href="{{ url_bots_translate }}?active__exact=1" class="ico-yes">{% trans 'Actives' %}</a></li>
        <li><a href="{{ url_bots_translate }}?active__exact=0" class="ico-no">{% trans 'Inactives' %}</a></li>
        {% if perms.bots.add_translate %}<li><a href="{% url 'admin:bots_translate_add' %}" class="ico-add">{% trans 'Add' %}</a></li>{% endif %}
      </ul>
    </li>{% endif %}

    {# PARTNER #}{% if perms.bots.view_partner or perms.bots.change_partner %}
    <li><hr/></li>
    <li><a href="{% url 'admin:bots_partner_changelist' %}" class="ico-partner">{% trans 'Partners' %}</a>
      <ul>
        <li><a href="{% url 'admin:bots_partner_changelist' %}?active__exact=1" class="ico-yes">{% trans 'Actives' %}</a></li>
        <li><a href="{% url 'admin:bots_partner_changelist' %}?active__exact=0" class="ico-no">{% trans 'Inactives' %}</a></li>
        {% if perms.bots.add_partner %}<li><a href="{% url 'admin:bots_partner_add' %}" class="ico-add">{% trans 'Add' %}</a></li>{% endif %}
      </ul>
    </li>{% endif %}

    {# PARTNER GROUPS #}{% if perms.bots.view_partnergroep or perms.bots.change_partnergroep %}
    <li><a href="{% url 'admin:bots_partnergroep_changelist' %}" class="ico-partnergroep">{% trans 'Partnergroups' %}</a>
      <ul>
        <li><a href="{% url 'admin:bots_partnergroep_changelist' %}?active__exact=1" class="ico-yes">{% trans 'Actives' %}</a></li>
        <li><a href="{% url 'admin:bots_partnergroep_changelist' %}?active__exact=0" class="ico-no">{% trans 'Inactives' %}</a></li>
        {% if perms.bots.add_partnergroep %}<li><a href="{% url 'admin:bots_partnergroep_add' %}" class="ico-add">{% trans 'Add' %}</a></li>{% endif %}
      </ul>
    </li>{% endif %}

    {# CONFIRMRULE #}{% if perms.bots.view_confirmrule or perms.bots.change_confirmrule %}
    <li><hr/></li>
    <li><a href="{% url 'admin:bots_confirmrule_changelist' %}" class="ico-confirm">{% trans 'Confirmrules' %}</a>
      <ul>
        <li><a href="{% url 'admin:bots_confirmrule_changelist' %}?active__exact=1" class="ico-yes">{% trans 'Actives' %}</a></li>
        <li><a href="{% url 'admin:bots_confirmrule_changelist' %}?active__exact=0" class="ico-no">{% trans 'Inactives' %}</a></li>
        {% if perms.bots.add_confirmrule %}<li><a href="{% url 'admin:bots_confirmrule_add' %}" class="ico-add">{% trans 'Add' %}</a></li>{% endif %}
      </ul>{% endif %}

    {# CCODE #}{% if perms.bots.view_ccode or perms.bots.change_ccode %}
    <li><hr/></li>
    <li><a href="{% url 'admin:bots_ccode_changelist' %}" class="ico-ccode">{% trans 'User Codes list' %}</a>
      {% if perms.bots.add_ccode %}<ul><li><a href="{% url 'admin:bots_ccode_add' %}" class="ico-add">{% trans 'Add' %}</a></li></ul>{% endif %}
    </li>{% endif %}

    {# CCODETRIGGER #}{% if perms.bots.view_ccodetrigger or perms.bots.change_ccodetrigger %}
    <li><a href="{% url 'admin:bots_ccodetrigger_changelist' %}" class="ico-ccodetrigger">{% trans 'User Code types' %}</a>
      {% if perms.bots.add_ccodetrigger %}<ul><li><a href="{% url 'admin:bots_ccodetrigger_add' %}" class="ico-add">{% trans 'Add' %}</a></li></ul>{% endif %}
    </li>{% endif %}
  </ul>
</li>{% endif %}

bots/bots/templates/bots/nav/custom.html
{% if custom_menus %}
<li><a>{{ custom_menuname }}</a>
    <ul>
    {% for key,value in custom_menus %}
	{% if value == '---' %}<li><hr/></li>
	{% else %}<li><a href="{{ value }}" >{{ key }}</a></li>{% endif %}
    {% endfor %}
    </ul>
</li>
{% endif %}

bots/bots/templates/bots/nav/documents.html
{% if perms.bots.view_ta %}{% load i18n %}<li><hr/></li>
<li><a href="{% url 'bots:document' %}/?allstatus=True" class="ico-docs">{% trans 'All phases' %}</a>
  <ul>
    <li><a href="{% url 'bots:document' %}/?allstatus=True&status=3" class="ico-docs">{% trans 'Discarded' %}</a>
    <li><a href="{% url 'bots:document' %}/?allstatus=True&status=200" class="ico-docs">{% trans 'Received' %}</a>
    <li><a href="{% url 'bots:document' %}/?allstatus=True&status=220" class="ico-docs">{% trans 'Infile' %}</a>
    <li><a href="{% url 'bots:document' %}/?allstatus=True&status=310" class="ico-docs">{% trans 'Parsed' %}</a>
    <li><a href="{% url 'bots:document' %}/?allstatus=True&status=320" class="ico-docs">{% trans 'Document-in' %}</a>
    <li><a href="{% url 'bots:document' %}/?allstatus=True&status=330" class="ico-docs">{% trans 'Document-out' %}</a>
    <li><a href="{% url 'bots:document' %}/?allstatus=True&status=400" class="ico-docs">{% trans 'Merged' %}</a>
    <li><a href="{% url 'bots:document' %}/?allstatus=True&status=500" class="ico-docs">{% trans 'Outfile' %}</a>
    <li><a href="{% url 'bots:document' %}/?allstatus=True&status=520" class="ico-docs">{% trans 'Send' %}</a>
  </ul>
</li>{% endif %}

bots/bots/templates/bots/nav/incoming.html
{% if perms.bots.view_filereport %}{% load i18n %}
<li><a{% if not bots_touchscreen %} href="{% url 'bots:incoming' %}"{% endif %} class="ico-incoming after-title" title="{% trans 'Incoming' %}"></a>
<ul>
  <li><a href="{% url 'bots:incoming' %}/?all" class="ico-incoming">{% trans 'Incoming' %}{% if not bots_touchscreen %} *{% endif %}</a></li>
  <li><a href="{% url 'bots:incoming' %}/?lastrun=1" class="ico-incoming">{% trans 'Last incoming' %}</a></li>
  <li><a href="{% url 'bots:incoming' %}/?statust=1" class="icon-err">{% trans 'Incoming errors' %}</a></li>
  <li><a href="{% url 'bots:incoming' %}/?select" class="ico-search">{% trans 'Select incoming' %}</a></li>
{% if perms.bots.view_ta %}  <li><hr/></li>
  <li><a href="{% url 'bots:document' %}/?status=320" class="ico-docsin">{% trans 'Document-in' %}</a></li>
  <li><a href="{% url 'bots:document' %}/?lastrun=1&status=320" class="ico-docsin">{% trans 'Last document-in' %}</a></li>
  <li><a href="{% url 'bots:document' %}/?select&status=320" class="ico-search">{% trans 'Select document' %}</a></li>{% endif %}
</ul>
</li>{% endif %}

bots/bots/templates/bots/nav/index.html
{% include 'bots/nav/incoming.html' %}
{% include 'bots/nav/outgoing.html' %}
{% include 'bots/nav/allruns.html' %}
{% include 'bots/nav/config.html' %}
{% include 'bots/nav/systasks.html' %}
{% include 'bots/nav/run.html' %}
{% include 'bots/nav/shortcuts.html' %}
{% include 'bots/nav/custom.html' %}
{% if django_version|default:'2' >= '4.2' %}<li style="float: right">{% include "admin/color_theme_toggle.html" %}&nbsp;</li>{% endif %}

bots/bots/templates/bots/nav/outgoing.html
{% if perms.bots.view_filereport %}{% load i18n %}
<li><a{% if not bots_touchscreen %} href="{% url 'bots:outgoing' %}"{% endif %} class="ico-outgoing after-title" title="{% trans 'Outgoing' %}"></a>
<ul>
  <li><a href="{% url 'bots:outgoing' %}/?all" class="ico-outgoing">{% trans 'Outgoing' %}{% if not bots_touchscreen %} *{% endif %}</a></li>
  <li><a href="{% url 'bots:outgoing' %}/?lastrun=1" class="ico-outgoing">{% trans 'Last outgoing' %}</a></li>
  <li><a href="{% url 'bots:outgoing' %}/?statust=1" class="icon-err">{% trans 'Outgoing errors' %}</a></li>
  <li><a href="{% url 'bots:outgoing' %}/?select" class="ico-search">{% trans 'Select outgoing' %}</a></li>
{% if perms.bots.view_ta %}  <li><hr/></li>
  <li><a href="{% url 'bots:document' %}/?status=330" class="ico-docsout">{% trans 'Document-out' %}</a></li>
  <li><a href="{% url 'bots:document' %}/?lastrun=1&status=330" class="ico-docsout">{% trans 'Last document-out' %}</a></li>
  <li><a href="{% url 'bots:document' %}/?select&status=330" class="ico-search">{% trans 'Select document' %}</a></li>{% endif %}
</ul>
</li>{% endif %}

bots/bots/templates/bots/nav/run.html
{% if perms.bots.change_mutex %}{# run bots-engine #}{% load i18n %}
<li><a class="ico-run after-title" title="{% trans 'Run' %}"></a>
<ul>
    <li><a href="{% url 'bots:runengine' %}/?clparameter=--new" class="ico-run">{% trans 'Run (only new)' %}</a>
    {% if menu_all_routes %}
        <ul>{% for route in menu_all_routes %}
            <li><a href="{% url 'bots:runengine' %}/?clparameter={{ route|urlencode:'' }}" class="ico-idroute">{{ route }}</a></li>
        {% endfor %}</ul>
    {% endif %}
    </li>
    <li><hr/></li>
    <li><a href="{% url 'bots:runengine' %}/?clparameter=--rereceive" class="ico-rereceive">{% trans 'Run user-indicated rereceives' %}</a></li>
    <li><a href="{% url 'bots:runengine' %}/?clparameter=--resend" class="ico-resend">{% trans 'Run user-indicated resends' %}</a></li>
{% if menu_automaticretrycommunication %}
    <li><hr/></li>
    <li><a href="{% url 'bots:runengine' %}/?clparameter=--automaticretrycommunication" class="ico-resend">{% trans 'Retry failed out-communications' %}</a></li>{% endif %}
{% if menu_cleanup %}
    <li><hr/></li>
    <li><a href="{% url 'bots:runengine' %}/?clparameter=--cleanup" class="ico-cleanup">{% trans 'Run cleanup' %}</a></li>
{% endif %}
</ul>
</li>{% endif %}

bots/bots/templates/bots/nav/systasks.html
{% if user.is_superuser %}{% load i18n %}
<li><a href="{% url 'admin:index' %}" class="ico-admin after-title" title="{% trans 'SysTasks' %}"></a>
<ul>
  <li><a class="ico-plugin">{% trans 'Plugins' %}</a>
    <ul>
      <li><a href="{% url 'bots:plugin' %}" class="ico-plugin">{% trans 'Read plugin' %}</a></li>
      <li><a href="{% url 'bots:plugout' %}" class="ico-plugout">{% trans 'Make plugin' %}</a></li>
      <li><a href="{% url 'bots:plugout' %}/backup" class="ico-plugout">{% trans 'Make backup plugin' %}</a></li>
    </ul>
  </li>
  <li><hr/></li>
  <li><a class="ico-config">{% trans 'Configuration' %}</a>
    <ul>
      <li><a href="{% url 'bots:plugin' %}/index" class="ico-read">{% trans 'Read configuration index' %}</a></li>
      <li><a href="{% url 'bots:plugout' %}/index" class="ico-write">{% trans 'Make configuration index' %}</a></li>
      <li><hr/></li>
      <li><a href="{% url 'bots:delete' %}" class="ico-del">{% trans 'Bulk delete' %}</a></li>
    </ul>
  </li>
  <li><hr/></li>
  {% include 'bots/nav/admin_auth.html' %}
  <li><hr/></li>
  <li><a href="{% url 'admin:bots_uniek_changelist' %}" class="ico-uniek">{% trans 'View/edit counters' %}</a></li>
  <li><a href="{% url 'bots:sendtestmail' %}" class="ico-sendmail">{% trans 'Send test report' %}</a></li>
  <li><hr/></li>
  <li><a href="{% url 'bots:logfiler' %}" target="_blank" class="ico-logs">{% trans 'Logs' %}</a>
    <ul>
      <li><a href="{% url 'bots:logfiler' %}/?engine" target="_blank" class="ico-translate">{% trans 'Engine logs' %}</a></li>
      <li><a href="{% url 'bots:logfiler' %}/?dirmonitor" target="_blank" class="ico-dirmonitor">{% trans 'Dirmonitor logs' %}</a></li>
      <li><a href="{% url 'bots:logfiler' %}/?jobqueue" target="_blank" class="ico-jobqueue">{% trans 'Jobqueue logs' %}</a></li>
      {% if 'Cheroot' in request.META.SERVER_SOFTWARE %}
      <li><a href="{% url 'bots:logfiler' %}/?webserver" target="_blank" class="ico-webserver">{% trans 'Webserver logs' %}</a></li>
      {% endif %}
    </ul>
  </li>
</ul>
</li>
{% endif %}