bots/bots/urls.py
# -*- coding: utf-8 -*-
"""
Bots urls
"""

from django.contrib import admin
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import views as auth_views
from django.urls import include, re_path

from . import botsglobal
from . import views
from . import healthcheck


staff_required = user_passes_test(lambda u: u.is_staff)
superuser_required = user_passes_test(lambda u: u.is_superuser)
run_permission = user_passes_test(lambda u: u.has_perm('bots.change_mutex'))


# Bots URL patterns
bots_paths = [
    # Health checks (no auth required - for K8s probes)
    re_path(r'^health/live/?$', healthcheck.health_live, name='health_live'),
    re_path(r'^health/ready/?$', healthcheck.health_ready, name='health_ready'),
    re_path(r'^health/startup/?$', healthcheck.health_startup, name='health_startup'),
    re_path(r'^health/ping/?$', healthcheck.health_ping, name='health_ping'),
    # Main views - login required
    re_path(r'^home.*', login_required(views.home), name='home'),
    re_path(r'^incoming.*', login_required(views.incoming), name='incoming'),
    re_path(r'^outgoing.*', login_required(views.outgoing), name='outgoing'),
    re_path(r'^detail.*', login_required(views.detail), name='detail'),
    re_path(r'^process.*', login_required(views.process), name='process'),
    re_path(r'^document.*', login_required(views.document), name='document'),
    re_path(r'^reports.*', login_required(views.reports), name='reports'),
    re_path(r'^confirm.*', login_required(views.confirm), name='confirm'),
    re_path(r'^filer.*', login_required(views.filer), name='filer'),
    re_path(r'^srcfiler.*', login_required(views.srcfiler), name='srcfiler'),
    re_path(r'^logfiler.*', login_required(views.logfiler), name='logfiler'),
    # only staff
    re_path(r'^runengine.+', run_permission(views.runengine), name='runengine'),
    # only superuser
    re_path(r'^delete.*', superuser_required(views.delete), name='delete'),
    re_path(r'^plugin/index.*', superuser_required(views.plugin_index), name='plugin_index'),
    re_path(r'^plugin.*', superuser_required(views.plugin), name='plugin'),
    re_path(r'^plugout/index.*', superuser_required(views.plugout_index), name='plugout_index'),
    re_path(r'^plugout/backup.*', superuser_required(views.plugout_backup), name='plugout_backup'),
    re_path(r'^plugout.*', superuser_required(views.plugout), name='plugout'),
    re_path(r'^sendtestmail.*', superuser_required(views.sendtestmailmanagers), name='sendtestmail'),
    # catch-all
    re_path(r'^.*', views.index),
]

auth_paths = [
    # Auth
    re_path(
        r"^login.*", auth_views.LoginView.as_view(template_name="admin/login.html"),
        name="login",
    ),
    re_path(
        r"^logout.*", auth_views.LogoutView.as_view(next_page="/"),
        name="logout",
    ),
]
if botsglobal.ini.getboolean("webserver", "menu_changepassword", True):
    auth_paths += [
        re_path(
            r"^password_change/$", auth_views.PasswordChangeView.as_view(),
            name="password_change",
        ),
        re_path(
            r"^password_change/done/$", auth_views.PasswordChangeDoneView.as_view(),
            name="password_change_done",
        ),
    ]


urlpatterns = auth_paths + [
    # only staff
    # do not show django admin root page
    # re_path(r'^admin/$', login_required(views.home)),
    # do not show django admin root page
    # re_path(r'^admin/bots/$', login_required(views.home)),
    re_path(r'^admin/', admin.site.urls),
    # Bots urls
    re_path('bots/', include((bots_paths, 'bots'), namespace='bots')),
    re_path(r'^.*', views.index),
]

# pylint: disable=invalid-name
handler500 = 'bots.views.server_error'

bots/bots/templates/bots/js/datetimepicker.html
{# 2019.05.03 LWA - https://github.com/xdan/datetimepicker #}
{% load i18n static %}{% get_current_language as LANGUAGE_CODE %}
<link rel="stylesheet" href="{% static "css/jquery.datetimepicker.min.css" %}">
<script src="{% static "admin/js/vendor/jquery/jquery.min.js" %}"></script>
<script src="{% static "js/jquery.datetimepicker.full.min.js" %}"></script>
<script>{# datetimepicker vars #}
jQuery.datetimepicker.setLocale('{{ LANGUAGE_CODE }}');
{# datetime_input_format|default:"Y-m-d H:i:s" #}
const datetime_input_format = '{{ DATETIME_INPUT_FORMAT }}';
const date_input_format = '{{ DATE_INPUT_FORMAT }}';
const time_input_format = '{{ TIME_INPUT_FORMAT }}';
const mindate = '{{ bots_mindate|date:DATE_INPUT_FORMAT }}';
const maxdate = '{{ bots_maxdate|date:DATE_INPUT_FORMAT }}';
const year_start = '{{ bots_mindate|date:"Y" }}';
const year_end = '{{ bots_maxdate|date:"Y" }}';
</script>
<script src="{% static "js/bots.datetimepicker.js" %}"></script>

bots/bots/templates/bots/js/dropdown.html
<script>{# Add dropdown event listners to all .dropdown ul #}
document.querySelectorAll('[data-field] .dropdown ul').forEach(function(ul) {
    ul.parentElement.addEventListener('mouseenter', dropdown, false);
});
</script>

bots/bots/templates/bots/js/filtered.html
<script>{# Add filteredfield class to filtered botstable tbody tr td #}
filteredtds();
</script>

bots/bots/templates/bots/js/fontsizes.html
<script>{# Create font sizes styles #}
var numbered = false;
var cbx_numbered = document.querySelector('#cbx_numbered');
if (cbx_numbered) {
    numbered = cbx_numbered.checked;
}
if (numbered) {
    var min_width = 1;
    document.querySelectorAll('div.content pre[id^=ta_co]').forEach(function(pre) {
        var width = String(pre.childElementCount).length;
        if (width > min_width) {
            min_width = width;
        }
    })
}

var font_styles = '';
Array.prototype.slice.call(document.querySelector('#id_fontsize').options).map(o => o.value).forEach(function(val) {
    font_styles += ' .fs' + val + ' { font-size: ' + val + '% !important;}';
    if (numbered) {
        calc_width = min_width * (Number(val) * 0.0055);
        font_styles += ' .fs' + val + '.numbered span { line-height: ' + Number(val) / 100 + 'rem;}';
        font_styles += ' .fs' + val + '.numbered span:before { min-width: ' + calc_width + 'rem;}';
    }
});
CreateStyle('fontstyles', font_styles);
document.querySelectorAll('#id_fontsize').forEach(function(sel) {
    SetFontSize(sel);
});
</script>

bots/bots/templates/bots/js/i18n.html
<script>{% load i18n %}
const trans = {
    'Date from': '{% trans 'Date from' %}',
    'Date until': '{% trans 'Date until' %}',
    'View': '{% trans 'View' %}',
    'View Route': '{% trans 'View Route' %}',
    'View Channel': '{% trans 'View Channel' %}',
    'View Partner': '{% trans 'View Partner' %}',
    'Add Partner': '{% trans 'Add Partner' %}',
    'View grammar': '{% trans 'View grammar' %}',
    'Download': '{% trans 'Download' %}',
    'Filter': '{% trans 'Filter' %}',
    'Exclude': '{% trans 'Exclude' %}',
    'Clear filter': '{% trans 'Clear filter' %}', 
    'Override existing selection': '{% trans 'Override existing selection' %}',
    'not found': '{% trans 'not found' %}',
    'No translate rule for ': '{% trans 'No translate rule for ' %}',
}


function gettext(txt) {
    return trans[txt] || txt;
}
</script>

bots/bots/templates/bots/js/refresh.html
{% if form and form.refresh and form.refresh.value %}{% with refresh=form.refresh.value %}
<script type="text/javascript">
$(document).ready(function() {
    setTimeout(function() {
        if (document.getElementById('id_refresh').value) {
            document.forms[0].submit();
        }
    }, {{ refresh }}*1000);
});
</script>{% endwith %}{% endif %}

bots/bots/templates/bots/js/urls.html
<script>{# bots js const (urls) #}
{% if perms.bots.view_partner %}const url_bots_partner = '{% url 'admin:bots_partner_changelist' %}';
const inactive_partners = {{ form.inactive_partners|safe|default:'[]' }};{% endif %}{# const partners = {{ form.partners|safe|default:'[]' }};#}
{% if perms.bots.add_partner %}const url_bots_partner_add = '{% url 'admin:bots_partner_add' %}';{% endif %}
{% if perms.bots.view_routes %}const url_bots_routes = '{% url 'admin:bots_routes_changelist' %}';{% endif %}
{% if perms.bots.view_channel %}const url_bots_channel = '{% url 'admin:bots_channel_changelist' %}';{% endif %}
{% if perms.bots.view_translate %}const url_bots_translate = '{% url 'admin:bots_translate_changelist' %}';{% endif %}
{% if perms.bots.add_translate %}const url_bots_translate_add = '{% url 'admin:bots_translate_add' %}';{% endif %}
{% if perms.bots.change_translate %}const url_bots_srcfiler = '{% url 'bots:srcfiler' %}';{% endif %}
{% if perms.bots.view_ta %}const url_bots_filer = '{% url 'bots:filer' %}';{% endif %}
</script>