bots/bots/urls.py
# -*- coding: utf-8 -*-
"""
Bots urls
"""

from django.contrib import admin
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import views as auth_views
from django.urls import include, re_path

from . import botsglobal
from . import views
from . import healthcheck


staff_required = user_passes_test(lambda u: u.is_staff)
superuser_required = user_passes_test(lambda u: u.is_superuser)
run_permission = user_passes_test(lambda u: u.has_perm('bots.change_mutex'))


# Bots URL patterns
bots_paths = [
    # Health checks (no auth required - for K8s probes)
    re_path(r'^health/live/?$', healthcheck.health_live, name='health_live'),
    re_path(r'^health/ready/?$', healthcheck.health_ready, name='health_ready'),
    re_path(r'^health/startup/?$', healthcheck.health_startup, name='health_startup'),
    re_path(r'^health/ping/?$', healthcheck.health_ping, name='health_ping'),
    # Main views - login required
    re_path(r'^home.*', login_required(views.home), name='home'),
    re_path(r'^incoming.*', login_required(views.incoming), name='incoming'),
    re_path(r'^outgoing.*', login_required(views.outgoing), name='outgoing'),
    re_path(r'^detail.*', login_required(views.detail), name='detail'),
    re_path(r'^process.*', login_required(views.process), name='process'),
    re_path(r'^document.*', login_required(views.document), name='document'),
    re_path(r'^reports.*', login_required(views.reports), name='reports'),
    re_path(r'^confirm.*', login_required(views.confirm), name='confirm'),
    re_path(r'^filer.*', login_required(views.filer), name='filer'),
    re_path(r'^srcfiler.*', login_required(views.srcfiler), name='srcfiler'),
    re_path(r'^logfiler.*', login_required(views.logfiler), name='logfiler'),
    # only staff
    re_path(r'^runengine.+', run_permission(views.runengine), name='runengine'),
    # only superuser
    re_path(r'^delete.*', superuser_required(views.delete), name='delete'),
    re_path(r'^plugin/index.*', superuser_required(views.plugin_index), name='plugin_index'),
    re_path(r'^plugin.*', superuser_required(views.plugin), name='plugin'),
    re_path(r'^plugout/index.*', superuser_required(views.plugout_index), name='plugout_index'),
    re_path(r'^plugout/backup.*', superuser_required(views.plugout_backup), name='plugout_backup'),
    re_path(r'^plugout.*', superuser_required(views.plugout), name='plugout'),
    re_path(r'^sendtestmail.*', superuser_required(views.sendtestmailmanagers), name='sendtestmail'),
    # catch-all
    re_path(r'^.*', views.index),
]

auth_paths = [
    # Auth
    re_path(
        r"^login.*", auth_views.LoginView.as_view(template_name="admin/login.html"),
        name="login",
    ),
    re_path(
        r"^logout.*", auth_views.LogoutView.as_view(next_page="/"),
        name="logout",
    ),
]
if botsglobal.ini.getboolean("webserver", "menu_changepassword", True):
    auth_paths += [
        re_path(
            r"^password_change/$", auth_views.PasswordChangeView.as_view(),
            name="password_change",
        ),
        re_path(
            r"^password_change/done/$", auth_views.PasswordChangeDoneView.as_view(),
            name="password_change_done",
        ),
    ]


urlpatterns = auth_paths + [
    # only staff
    # do not show django admin root page
    # re_path(r'^admin/$', login_required(views.home)),
    # do not show django admin root page
    # re_path(r'^admin/bots/$', login_required(views.home)),
    re_path(r'^admin/', admin.site.urls),
    # Bots urls
    re_path('bots/', include((bots_paths, 'bots'), namespace='bots')),
    re_path(r'^.*', views.index),
]

# pylint: disable=invalid-name
handler500 = 'bots.views.server_error'

bots/bots/templates/bots/base.html
{% extends "admin/base.html" %}
{% load i18n static %}

{% block extrahead %}{{ block.super }}
{% include "bots/js/urls.html" %}
{% include "bots/js/i18n.html" %}
{% include "bots/js/datetimepicker.html" %}
<script src="{% static "js/botstable.js" %}"></script>
{% if user.is_staff and perms.bots %}<script src="{% static "js/bots.staff.js" %}"></script>{% endif %}
<script>window.onload = sorted;</script>
{% endblock %}

{% block bodyclass %}{{ block.super }} bots{% endblock %}

{% block content_title %}{% endblock %}

{% block content %}
<form action="{{ form.action }}" id="viewform" method="post">{% csrf_token %}
{% block bots_title %}<h1><a href="#" title="{% trans 'Top' %}">{{ title }}</a> {% include "bots/selection/view.html" %}</h1>{% endblock %}
{% include "bots/paginator.html" %}
{% include 'bots/button_back_close.html' %}
{% block bots_submit %}
{% if perms.bots.change_mutex and not form.admlink.is_hidden %}{% include 'bots/botstable/field/checkbox.html' with field=form.admlink %}{% endif %}
{% if form.popup %}{% include 'bots/botstable/field/checkbox.html' with field=form.popup %}{% endif %}
{% if form.lastrun %}{% include 'bots/botstable/field/checkbox.html' with field=form.lastrun %}{% endif %}
{% if form.idta.is_hidden %}{% include 'bots/botstable/field/hidden.html' with field=form.idta %}{% endif %}
{% endblock %}{% for hidden in form.hidden_fields %}{{ hidden }}
{% endfor %}{{ form.errors }}
<div>
<table id="botstable">
{% block botstable %}
<thead></thead>
<tbody>{% for row in queryset.object_list %}
<tr class="{% cycle 'row1' 'row2' %} botstrstatus{{ row.statust }}"></tr>{% endfor %}
</tbody>{% endblock %}
</table>
</div>
<br />
{# include "bots/paginator.html" with footer=True #}
</form>
{% endblock %}

{% block footer %}{{ block.super }}
{% include "bots/js/dropdown.html" %}
{% include "bots/js/filtered.html" %}
{% include "bots/js/refresh.html" %}
{% endblock %}

bots/bots/templates/bots/button_back_close.html
{% include 'bots/button_back.html' %}

bots/bots/templates/bots/button_cancel_close.html
{% if is_popup %}{% include 'bots/button_close.html' %}
{% else %}{% include 'bots/button_cancel.html' %}
{% endif %}

bots/bots/templates/bots/confirm.html
{% extends "bots/base.html" %}
{% load i18n botsfilters %}

{% block bodyclass %}{{ block.super }} confirm{% endblock %}

{% block bots_title %}
<h1 class="ico-{% if form.confirmidta.value == 0 %}pending{% else %}confirmed{{ form.confirmed.value }}{% endif %}"><a href="#" title="{% trans 'Top' %}">{{ title }}</a> {% include "bots/selection/view.html" %}</h1>
{% endblock %}

{% block bots_submit %}
<button class="button ico-incoming" name="2incoming">{% trans 'Incoming (same selection)' %}</button>
<button class="button ico-outgoing" name="2outgoing">{% trans 'Outgoing (same selection)' %}</button>
{% if form.confirmidta.value < 1 %}<button class="button ico-no" onclick="document.getElementById('id_confirmidta').value='';">{% trans 'All confirmations' %}</button>{% endif %}
{% if form.confirmidta.value != -1 %}<button class="button ico-confirmed" onclick="document.getElementById('id_confirmidta').value=-1;">{% trans 'Manual confirm' %}</button>{% endif %}
{% if form.confirmidta.value != 0 %}<button class="button ico-pending" onclick="document.getElementById('id_confirmidta').value=0;">{% trans 'Pending (same selection)' %}</button>{% endif %}
{{ block.super }}
{% if not perms.bots.change_mutex %}{% include 'bots/botstable/field/hidden.html' with field=form.idroute %}
{% include 'bots/botstable/field/hidden.html' with field=form.fromchannel %}
{% include 'bots/botstable/field/hidden.html' with field=form.tochannel %}{% endif %}
{% endblock %}

{% block botstable %}
<thead>
<tr>
    {% include 'bots/botstable/thead/selall.html' %}
    {% include 'bots/botstable/thead/field.html' with field=form.idta %}
    {% include 'bots/botstable/thead/field.html' with field=form.confirmed %}
    <th id="th_ts"><button class="botsheader ico-ts" name="order" value="ts">{% trans 'Date/time' %}</button></th>
    <th id="th_filename"><button class="botsheader ico-file" name="order" value="filename" >{% trans 'File' %}</button></th>
    <th id="th_reference"><button class="botsheader" name="order" value="reference" >{% trans 'Reference' %}</button></th>
    {% include 'bots/botstable/thead/field.html' with field=form.confirmtype %}
    {% include 'bots/botstable/thead/field.html' with field=form.confirmidta %}
    {% include 'bots/botstable/thead/field.html' with field=form.editype %}
    {% include 'bots/botstable/thead/field.html' with field=form.messagetype %}
    {% if perms.bots.change_mutex %}{% include 'bots/botstable/thead/field.html' with field=form.idroute %}
    {% include 'bots/botstable/thead/field.html' with field=form.fromchannel %}
    {% include 'bots/botstable/thead/field.html' with field=form.tochannel %}{% endif %}
    {% include 'bots/botstable/thead/field.html' with field=form.frompartner %}
    {% include 'bots/botstable/thead/field.html' with field=form.topartner %}
</tr>
<tr>
    {% if not form.actions.is_hidden %}<th></th>{% endif %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.idta %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.confirmed get_field_display=True icon="ico-confirmed" cssclass=form.confirmed.value %}
    {% include 'bots/botstable/thead/datefields.html' %}
    {% include 'bots/botstable/thead/textfield.html' with field=form.filename %}
    {% include 'bots/botstable/thead/textfield.html' with field=form.reference %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.confirmtype get_field_display=True %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.confirmidta %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.editype %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.messagetype %}
    {% if perms.bots.change_mutex %}{% include 'bots/botstable/thead/filtered.html' with field=form.idroute %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.fromchannel %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.tochannel %}{% endif %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.frompartner %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.topartner %}
</tr>
</thead>
<tbody>{% for row in queryset.object_list %}
<tr class="{% cycle 'row1' 'row2' %}">
    {% include 'bots/botstable/td/sel.html' %}
    <td><div class="dropdown">
      {% if perms.bots.view_ta %}<a href="{% url 'bots:detail' %}/?outidta={{ row.idta }}" name="bots_detail_{{ row.idta }}" onclick="return popup(this, '95%', '75%', '&popup=1')" title="{% trans 'View details' %}: {{ row.idta }}" class="button ico-{% if row.confirmidta == 0 %}pending{% else %}confirmed{{ row.confirmed }}{% endif %}">{{ row.idta }}</a>
      {% else %}<button type="button" class="button ico-confirmed{{ row.confirmed }}">{{ row.idta }}</button>{% endif %}
      {% if not row.confirmidta and perms.bots.change_ta %}<ul>
        <li><button value="{{ row.idta }}" class="ico-confirmed" onclick="if (!confirm(this.innerText + ': ' + this.value)){return false;}; this.name = 'confirm';">{% trans 'Confirm manual' %}</button></li>
      </ul>{% endif %}
    </div></td>
    {% include 'bots/botstable/td/confirmed.html' %}
    {% include 'bots/botstable/td/ts.html' %}
    {% include 'bots/botstable/td/filename.html' %}
    {% include 'bots/botstable/td/reference.html' %}
    {% include 'bots/botstable/td/confirmtype.html' %}
    <td>{% include 'bots/link/confirmation.html' with ta=row %}</td>
    {% include 'bots/botstable/td/editype.html' %}
    {% include 'bots/botstable/td/messagetype.html' %}
    {% if perms.bots.change_mutex %}{% include 'bots/botstable/td/idroute.html' %}
    {% include 'bots/botstable/td/fromchannel.html' %}
    {% include 'bots/botstable/td/tochannel.html' %}{% endif %}
    {% include 'bots/botstable/td/frompartner.html' %}
    {% include 'bots/botstable/td/topartner.html' %}
</tr>
{% endfor %}</tbody>
{% endblock %}

bots/bots/templates/bots/outgoing.html
{% extends "bots/base.html" %}
{% load i18n botsfilters %}

{% block bodyclass %}{{ block.super }} outgoing{% endblock %}

{% block bots_submit %}
<button class="button ico-incoming" name="2incoming">{% trans 'Incoming (same selection)' %}</button>
<button class="button icon-err" name="2process">{% trans 'Process Errors (same selection)' %}</button>
<button class="button ico-confirm" name="2confirm">{% trans 'Confirm (same selection)' %}</button>
{{ block.super }}
{% if perms.bots.change_mutex %}<button class="button ico-yes" name="rereceiveall">{% trans 'Resend All' %}</button>
{% include 'bots/botstable/field/text.html' with field=form.errortext %}
{% else %}
{% include 'bots/botstable/field/text.html' with field=form.errortext %}
{% include 'bots/botstable/field/hidden.html' with field=form.idroute %}
{% include 'bots/botstable/field/hidden.html' with field=form.tochannel %}
{% include 'bots/botstable/field/hidden.html' with field=form.retransmit %}{% endif %}
{% endblock %}

{% block botstable %}
<thead>
<tr>
    {% include 'bots/botstable/thead/selall.html' %}
    {% include 'bots/botstable/thead/field.html' with field=form.idta %}
    {% include 'bots/botstable/thead/field.html' with field=form.statust %}
    {% if perms.bots.change_mutex %}<th id="th_retransmit"><button class="botsheader center" name="order" value="retransmit" title="{% trans 'Sort by' %} {{ form.retransmit.label }}">Re*</button></th>{% endif %}
    <th id="th_ts"><button class="botsheader ico-ts" name="order" value="ts" title="{% trans 'Sort by' %} {% trans 'Date/time' %}">{% trans 'Date/time' %}</button></th>
    <th id="th_numberofresends"><button class="botsheader" name="order" value="numberofresends">{% trans '#send' %}</button></th>
    <th id="th_filename"><button class="botsheader ico-outfile" name="order" value="filename" title="{% trans 'Sort by' %} {% trans 'OutFile' %}">{% trans 'OutFile' %}</button></th>
    <th id="th_nrmessages"><button class="botsheader" name="order" value="nrmessages">{% trans '#mes' %}</button></th>
    {% include 'bots/botstable/thead/field.html' with field=form.editype %}
    {% include 'bots/botstable/thead/field.html' with field=form.messagetype %}
    {% if perms.bots.change_mutex %}{% include 'bots/botstable/thead/field.html' with field=form.idroute %}
    {% include 'bots/botstable/thead/field.html' with field=form.tochannel %}{% endif %}
    {% include 'bots/botstable/thead/field.html' with field=form.frompartner %}
    {% include 'bots/botstable/thead/field.html' with field=form.topartner %}
    <th id="th_reference"><button class="botsheader" name="order" value="reference" title="{% trans 'Sort by' %} {% trans 'Reference' %}">{% trans 'Reference' %}</button></th>
    <th id="th_charset"><button class="botsheader" name="order" value="charset">{% trans 'Charset' %}</button></th>
    <th id="th_contenttype"><button class="botsheader" name="order" value="contenttype">{% trans 'Contenttype' %}</button></th>
    <th id="th_testindicator"><button class="botsheader" name="order" value="testindicator">{% trans 'Test' %}</button></th>
</tr>
<tr>
    {% if not form.actions.is_hidden %}<th></th>{% endif %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.idta %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.statust get_field_display=True thclass="center" %}
    {% if perms.bots.change_mutex %}{% include 'bots/botstable/thead/checkbox.html' with field=form.retransmit %}{% endif %}
    {% include 'bots/botstable/thead/datefields.html' %}
    <th></th>
    {% include 'bots/botstable/thead/textfield.html' with field=form.filename %}
    <th></th>
    {% include 'bots/botstable/thead/filtered.html' with field=form.editype %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.messagetype %}
    {% if perms.bots.change_mutex %}{% include 'bots/botstable/thead/filtered.html' with field=form.idroute %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.tochannel %}{% endif %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.frompartner %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.topartner %}
    {% include 'bots/botstable/thead/textfield.html' with field=form.reference %}
    <th></th>
    <th></th>
    {% include 'bots/botstable/thead/textfield.html' with field=form.testindicator %}
</tr>
</thead>
<tbody>{% for row in queryset.object_list %}
<tr class="{% cycle 'row1' 'row2' %} botstrstatus{{ row.statust }}">
    {% include 'bots/botstable/td/sel.html' %}
    <td><div class="dropdown">
      {% if perms.bots.view_ta %}<a href="{% url 'bots:detail' %}/?outidta={{ row.idta }}" onclick="return popup(this, '95%', '75%', '&popup=1')" title="Bots {% trans 'details' %}: {{ row.idta }}" class="button ico-out block">{{ row.idta }}</a>{% else %}<button class"button block">{{ row.idta }}</button>{% endif %}
      <ul>{% if perms.bots.view_report %}
        {% if user.is_staff %}<li><a class="ico-log" href="{% url 'bots:logfiler' %}/?engine=&outidta={{ row.idta }}" target="_blank">{% trans 'View log' %}</a></li>{% endif %}
        <li><a class="ico-reports" href="{% url 'bots:reports' %}/?outidta={{ row.idta }}&popup=1" target="_blank">{% trans 'View report' %}</a></li>{% endif %}
        {% if perms.bots.change_mutex %}<li><button name="resend" value="{{ row.idta }}" class="ico-resend">{% trans 'Resend' %}</button></li>
        {% if row.statust == 1 %}<li><button name="noautomaticretry" value="{{ row.idta }}" class="ico-no">{% trans 'No automatic retry' %}</button></li>{% endif %}{% endif %}
        {% comment %}{# Delete only incoming filereport, not outgoing ta here #}
        {% if perms.bots.delete_ta %}<li><button class="botsheader" name="delete" value="{{ row.idta }}">{% trans 'Delete file' %}</button></li>{% endif %}
        {% endcomment %}
      </ul>
    </div></td>
    {% include 'bots/botstable/td/statust.html' %}
    {% if perms.bots.change_mutex %}{% include 'bots/botstable/td/retransmit.html' with td_title=form.retransmit.label %}{% endif %}
    {% include 'bots/botstable/td/ts.html' %}
    <td>{{ row.numberofresends }}</td>
    {% include 'bots/botstable/td/filename.html' %}
    <td>{{ row.nrmessages }}</td>
    {% include 'bots/botstable/td/editype.html' %}
    {% include 'bots/botstable/td/messagetype.html' %}
    {% if perms.bots.change_mutex %}{% include 'bots/botstable/td/idroute.html' %}
    {% include 'bots/botstable/td/tochannel.html' %}{% endif %}
    {% include 'bots/botstable/td/frompartner.html' %}
    {% include 'bots/botstable/td/topartner.html' %}
    {% include 'bots/botstable/td/reference.html' %}
    <td>{{ row.charset }}</td>
    <td>{{ row.contenttype }}</td>
    <td>{{ row.testindicator }}</td>
</tr>{% if row.errortext %}
<tr class="{% cycle 'row1' 'row2' %} botstrstatus{{ row.statust }} errortext" id="tr{{ row.idta }}">
    <td></td>{% if not form.actions.is_hidden %}<td></td>{% endif %}
    <td align="left" class="va-top" colspan="{% if perms.bots.change_mutex %}16{% else %}13{% endif %}">{% include "bots/ta_errortext.html" with truncaterr=True %}</td>
</tr>{% endif %}
{% endfor %}</tbody>
{% endblock %}

bots/bots/templates/bots/plugin.html
{% extends "admin/base.html" %}
{% load i18n %}

{% block content %}
<br/>
<h1 class="ico-plugin">{% trans 'Read a plugin' %}</h1>
<br/>
<p>{% trans 'Select a plugin from your file system' %}:</p>
<form action="{% url 'bots:plugin' %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
{{ form }}
<br/>
<br/>
<br/>
{% include 'bots/button_cancel_close.html' %}
<button name="submit" class="button ico-read" onclick="return (document.getElementById('id_file').value && confirm('{% trans 'Read' %}: ' + document.getElementById('id_file').files[0].name + ' ?'));">{% trans 'Read' %}</button>
</form>
{% endblock %}

bots/bots/templates/bots/plugin_index.html
{% extends "admin/base.html" %}
{% load i18n %}

{% block content %}
<br/>
<h1 class="ico-plugin">{% trans 'Confirm reading index file' %}</h1>
<br/>
<p>{% trans 'Please confirm reading the default index file bots/usersys/index.py. This might change your configuration !' %}</p>
<form action="{% url 'bots:plugin' %}/index" method="POST" enctype="multipart/form-data">{% csrf_token %}
    <br/>&nbsp;
    <button name="cancel" class="button ico-no">{% trans 'Cancel' %}</button>
    <button name="submit" class="button ico-read" onclick="return confirm('{% trans 'Read configuration index ?' %}');">{% trans 'Confirm read' %}</button>
</form>
{% endblock %}

bots/bots/templates/bots/reports.html
{% extends "bots/base.html" %}
{% load i18n %}

{% block bodyclass %}{{ block.super }} reports{% endblock %}

{% block botstable %}
<thead>
<tr>
    <th id="th_selall">{% if not form.actions.is_hidden %}<input type="checkbox" name="selall" onchange="checkall(this, 'sel')">{% endif %}</th>
    {% include 'bots/botstable/thead/field.html' with field=form.status %}
    <th id="th_ts"><button class="botsheader ico-ts" name="order" value="ts">{% trans 'Date/time' %}</button></th>
    {% include 'bots/botstable/thead/field.html' with field=form.type %}
    <th id="th_lastreceived"><button class="botsheader" name="order" value="lastreceived">{% trans '#in' %}</button></th>
    <th id="th_send"><button class="botsheader" name="order" value="send">{% trans '#out' %}</button></th>
    <th id="th_filesize"><button class="botsheader" name="order" value="filesize">{% trans 'Size' %}</button></th>
    <th id="th_processerrors"><button class="botsheader ico-err" name="order" value="processerrors">{% trans 'Error' %}</button></th>
    <th id="th_rsrv1"><button class="botsheader ico-run" name="order" value="rsrv1">{% trans 'Commandline' %}</button></th>
    {% include 'bots/botstable/thead/field.html' with field=form.acceptance %}
</tr>
<tr>
    <th></th>
    {% include 'bots/botstable/thead/filtered.html' with field=form.status get_field_display=True %}
    {% include 'bots/botstable/thead/datefields.html' %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.type get_field_display=True %}
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    {% include 'bots/botstable/thead/textfield.html' with field=form.rsrv1 %}
    {% include 'bots/botstable/thead/filtered.html' with field=form.acceptance get_field_display=True %}
</tr>
</thead>
<tbody class="reports">{% for row in queryset.object_list %}
<tr class="{% cycle 'row1' 'row2' %}{% if row.status %} botstrstatus1{% endif %}">
    <td><div class="dropdown">{% if not form.actions.is_hidden %}<input type="checkbox" id="{{ row.idta }}" name="sel" value="{{ row.idta }}" onclick="checktr(this)"><label for="{{ row.idta }}" class="icon-star" title="Select {{ row.idta }}"></label>{% else %}<span class="icon-star"></span>{% endif %}
      <ul>
        {% if user.is_staff %}<li><a class="ico-log" href="{% url 'bots:logfiler' %}/?engine={{ row.idta }}" target="_blank">{% trans 'View log' %}</a></li>{% endif %}{% if row.lastreceived %}
        <li><a href="{% url 'bots:incoming' %}/?reportidta={{ row.idta }}&popup=1" target="_blank" class="ico-incoming">{% trans 'View incoming' %}</a></li>
        <li><a href="{% url 'bots:outgoing' %}/?reportidta={{ row.idta }}&popup=1" target="_blank" class="ico-outgoing">{% trans 'View out-communication' %}</a></li>{% endif %}
        {% if perms.bots.delete_report %}<li><button name="delete" value="{{ row.idta }}" class="ico-trash" onclick="return confirm(this.innerText + ': ' + this.value)">{% trans 'Delete' %} {% trans 'report' %}</button></li>{% endif %}
      </ul>
    </div></td>
    <td data-field="status" data-value="{% if not row.status %}0"><div class="dropdown icon-yes{% else %}1"><div class="dropdown {% if row.lasterror or row.lastok or row.lastopen %}icon-no{% else %}icon-alert{% endif %}{% endif %}"><ul></ul></div></td>
    {% include 'bots/botstable/td/ts.html' %}
    {% include 'bots/botstable/td/td.html' with field=form.type value=row.type %}
    <td>{% if row.lastreceived %}<a href="{% url 'bots:incoming' %}/?reportidta={{ row.idta }}" class="button" title="{% trans 'View incoming' %}">{{ row.lastreceived }}</a>{% else %}{{ row.lastreceived }}{% endif %}</td>
    <td>{% if row.send %}<a href="{% url 'bots:outgoing' %}/?reportidta={{ row.idta }}" class="button" title="{% trans 'View outgoing' %}">{{ row.send }}</a>{% else %}{{ row.send }}{% endif %}</td>
    <td>{% if row.filesize %}{{ row.filesize|filesizeformat }}{% endif %}</td>
    <td><ul class="reporterrs">{% if row.lasterror %}<li><a href="{% url 'bots:incoming' %}/?reportidta={{ row.idta }}&statust=1" class="button ico-err" title="{% trans 'View file errors' %}">{{ row.lasterror }} {% trans 'files with errors' %}</a></li>{% endif %}
      {% if row.lastok %}<li><a href="{% url 'bots:incoming' %}/?reportidta={{ row.idta }}&statust=2" class="button ico-err" title="{% trans 'View incoming' %}">{{ row.lastok }} {% trans 'files got stuck' %}</a></li>{% endif %}
      {% if row.lastopen %}<li><a href="{% url 'bots:incoming' %}/?reportidta={{ row.idta }}&statust=0" class="button ico-err" title="{% trans 'View incoming' %}">{{ row.lastopen }} {% trans 'system errors' %}</a></li>{% endif %}
      {% if row.processerrors %}<li><a href="{% url 'bots:process' %}/?reportidta={{ row.idta }}" class="button ico-err" title="{% trans 'View process errors' %}">{{ row.processerrors }} {% trans 'errors in processes' %}</a></li>{% endif %}
      {% if row.status and row.lastreceived and not row.send %}<li><a href="{% url 'bots:outgoing' %}/?reportidta={{ row.idta }}&statust=1&popup=1" target="_blank" class="button ico-err">{% trans 'View out-communication errors' %}</a></li>{% endif %}
    </ul></td>
    {% include 'bots/botstable/td/rsrv1.html' %}
    <td>{% if row.acceptance %}<b class="ico-yes"></b>{% endif %}</td>
</tr>
{% endfor %}</tbody>
{% endblock %}

bots/bots/templates/bots/ta_errortext.html
<div class="errortext">
{% if truncaterr %}{{ row.errortext|truncatechars:2048|linebreaks }}{% else %}{{ row.errortext|linebreaks }}{% endif %}
</div>