bots/bots/urls.py
# -*- coding: utf-8 -*-
"""
Bots urls
"""

from django.contrib import admin
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import views as auth_views
from django.urls import include, re_path

from . import botsglobal
from . import views
from . import healthcheck


staff_required = user_passes_test(lambda u: u.is_staff)
superuser_required = user_passes_test(lambda u: u.is_superuser)
run_permission = user_passes_test(lambda u: u.has_perm('bots.change_mutex'))


# Bots URL patterns
bots_paths = [
    # Health checks (no auth required - for K8s probes)
    re_path(r'^health/live/?$', healthcheck.health_live, name='health_live'),
    re_path(r'^health/ready/?$', healthcheck.health_ready, name='health_ready'),
    re_path(r'^health/startup/?$', healthcheck.health_startup, name='health_startup'),
    re_path(r'^health/ping/?$', healthcheck.health_ping, name='health_ping'),
    # Main views - login required
    re_path(r'^home.*', login_required(views.home), name='home'),
    re_path(r'^incoming.*', login_required(views.incoming), name='incoming'),
    re_path(r'^outgoing.*', login_required(views.outgoing), name='outgoing'),
    re_path(r'^detail.*', login_required(views.detail), name='detail'),
    re_path(r'^process.*', login_required(views.process), name='process'),
    re_path(r'^document.*', login_required(views.document), name='document'),
    re_path(r'^reports.*', login_required(views.reports), name='reports'),
    re_path(r'^confirm.*', login_required(views.confirm), name='confirm'),
    re_path(r'^filer.*', login_required(views.filer), name='filer'),
    re_path(r'^srcfiler.*', login_required(views.srcfiler), name='srcfiler'),
    re_path(r'^logfiler.*', login_required(views.logfiler), name='logfiler'),
    # only staff
    re_path(r'^runengine.+', run_permission(views.runengine), name='runengine'),
    # only superuser
    re_path(r'^delete.*', superuser_required(views.delete), name='delete'),
    re_path(r'^plugin/index.*', superuser_required(views.plugin_index), name='plugin_index'),
    re_path(r'^plugin.*', superuser_required(views.plugin), name='plugin'),
    re_path(r'^plugout/index.*', superuser_required(views.plugout_index), name='plugout_index'),
    re_path(r'^plugout/backup.*', superuser_required(views.plugout_backup), name='plugout_backup'),
    re_path(r'^plugout.*', superuser_required(views.plugout), name='plugout'),
    re_path(r'^sendtestmail.*', superuser_required(views.sendtestmailmanagers), name='sendtestmail'),
    # catch-all
    re_path(r'^.*', views.index),
]

auth_paths = [
    # Auth
    re_path(
        r"^login.*", auth_views.LoginView.as_view(template_name="admin/login.html"),
        name="login",
    ),
    re_path(
        r"^logout.*", auth_views.LogoutView.as_view(next_page="/"),
        name="logout",
    ),
]
if botsglobal.ini.getboolean("webserver", "menu_changepassword", True):
    auth_paths += [
        re_path(
            r"^password_change/$", auth_views.PasswordChangeView.as_view(),
            name="password_change",
        ),
        re_path(
            r"^password_change/done/$", auth_views.PasswordChangeDoneView.as_view(),
            name="password_change_done",
        ),
    ]


urlpatterns = auth_paths + [
    # only staff
    # do not show django admin root page
    # re_path(r'^admin/$', login_required(views.home)),
    # do not show django admin root page
    # re_path(r'^admin/bots/$', login_required(views.home)),
    re_path(r'^admin/', admin.site.urls),
    # Bots urls
    re_path('bots/', include((bots_paths, 'bots'), namespace='bots')),
    re_path(r'^.*', views.index),
]

# pylint: disable=invalid-name
handler500 = 'bots.views.server_error'

bots/bots/templates/bots/link/add_partner.html
{% if perms.bots.add_partner %}{% load i18n %}
<a title="{% trans 'Add' %} Bots {% trans 'partner'|capfirst %}" onclick="return add_partner(this)" class="{% if as_link %}botslink{% else %}button ico-add-partner botsstatus1 {{ cssclass }}{% endif %}">{{ idpartner }}</a>
{% else %}<span class="ico-{{ fromto }}partner">{{ idpartner }}</span>{% endif %}

bots/bots/templates/bots/link/change_channel.html
{% if perms.bots.view_channel %}{% load i18n %}
<a title="Bots {% trans 'channel'|capfirst %}: {{ idchannel }}" onclick="return view_channel(this)" class="{% if as_link %}botslink{% else %}button ico-{{ fromto }}channel {{ cssclass }}{% endif %}" data-after=" ({{ channel_type }})">{{ idchannel }}</a>{% else %}<span class="ico-{{ fromto }}channel" data-after=" ({{ channel_type }})">{{ idchannel }}</span>{% endif %}

bots/bots/templates/bots/link/channel.html
{% if idchannel %}{% if channel_type %}{% if admlink %}{% include 'bots/link/change_channel.html' %}
{% else %}<span class="ico-{{ fromto }}channel" data-after=" ({{ channel_type }})">{{ idchannel }}</span>{% endif %}
{% else %}<span class="ico-{{ fromto }}channel after-err">{{ idchannel }}</span>{% endif %}{% endif %}

bots/bots/templates/bots/link/confirmation.html
{% load i18n %}{% if ta.confirmidta > 0 %}{% include 'bots/link/filer.html' with idta=ta.confirmidta %}
{% elif ta.confirmidta < 0 %}{% trans 'Manual confirm' %}{% elif ta.confirmasked %}{% trans 'Pending ...' %} <button type="button" class="button ico-reload pad2" title="{% trans 'Refresh' %}" onclick="location.reload()"></button>{% endif %}

bots/bots/templates/bots/link/detail.html
{% if perms.bots.view_ta and ta %}{% load i18n %}
<a class="button pad8" title="Bots {% trans 'Details' %} {{ ta.idta }}" href="{% url 'bots:detail' %}/?{% if ta.has_previous %}out{% else %}in{% endif %}idta={{ ta.idta }}&popup=1" onclick="return popup(this, '95%', '75%')">{% trans 'details' %}</a>{% endif %}

bots/bots/templates/bots/link/document.html
{% if perms.bots.view_ta and idta %}{% load i18n %}
<a href="{% url 'bots:document' %}/?idta={{ idta }}" onclick="return popup(this, '95%', '60%', '&popup=1')" title="Bots {% trans 'document' %}: {{ idta }}" class="{% if as_link %}botslink{% else %}button ico-doc{{ inorout }}{% endif %} {{ cssclass|default:"pad2" }}">{{ text|default:idta }}</a>
{% else %}{{ text|default:idta }}{% endif %}

bots/bots/templates/bots/link/downlfile.html
{% if perms.bots.view_ta %}{% load i18n botsfilters %}
<a href="{% url 'bots:filer' %}/?action=downl&amp;idta={{ idta }}" class="botslink ico-save" title="{% trans 'Download' %} {{ filename|shortpath|default:idta }}"></a>{% endif %}

bots/bots/templates/bots/link/grammarsrc.html
{% if editype and editype != 'raw' and editype != 'db' and messagetype %}{% load i18n %}
<a onmouseenter="view_src(this, '{{ typeofgrammarfile|default:"grammars" }}', '{{ editype }}', '{{ messagetype }}')" onclick="this.onmouseenter(){% if is_popup %}; return popup(this, '80%', '90%'){% endif %}" title="{% trans 'View source' %}" class="icon-py {% if as_link %}botslink{% else %}button{% endif %}">{{ text|default:messagetype }}</a>{% else %}{{ messagetype }}{% endif %}

bots/bots/templates/bots/link/inorout.html
{% with text=ta.get_status_display idta=ta.idta %}
{% if ta.status == 200 %}{% include 'bots/link/incoming.html' %}
{% elif ta.status == 320 or ta.status == 330 %}{% include 'bots/link/document.html' with inorout=ta.status %}
{% elif ta.status == 520 %}{% include 'bots/link/outgoing.html' %}
{% else %}{{ text }}{% endif %}{% endwith %}

bots/bots/templates/bots/link/logfiler.html
{% load i18n static %}
<a href="{% url 'bots:logfiler' %}/?{{ logname }}={{ value }}" title="{% blocktrans %}View {{ logname }} log{% endblocktrans %} {{ value }}" target="_blank"{% if popup %} onclick="return popup(this)"{% endif %} class="button ico-log ico-150 nobg"></a>

bots/bots/templates/bots/link/messagetype.html
{% if admlink and perms.bots.change_translate %}{% include 'bots/link/grammarsrc.html' %}
{% else %}{{ messagetype }}{% endif %}

bots/bots/templates/bots/link/outgoing.html
{% if perms.bots.view_ta and idta %}{% load i18n %}
<a href="{% url 'bots:outgoing' %}?idta={{ idta }}" onclick="return popup(this, '95%', '60%', '&popup=1')" title="Bots {% trans 'Outgoing' %} {{ idta }}" class="button ico-out {{ cssclass|default:"pad2" }}">{{ text|default:idta }}</a>
{% else %}{{ text|default:idta }}{% endif %}

bots/bots/templates/bots/link/partner.html
{% if idpartner %}{% if admlink and perms.bots.view_partner %}
{% if idpartner in partners %}{% include 'bots/link/change_partner.html' %}
{% elif idpartner in inactive_partners %}{% include 'bots/link/change_partner.html' with cssclass=cssclass|add:" botsstatus2" %}
{% else %}{% include 'bots/link/add_partner.html' %}{% endif %}
{% else %}<span class="ico-{{ fromto }}partner">{{ idpartner }}</span>{% endif %}{% endif %}

bots/bots/templates/bots/link/translate.html
{% if perms.bots.change_translate and tscript and messagetype %}{% load i18n botsfilters %}
{% with translate=messagetype|get_translate:tscript %}{% if translate and translate.pk %}
{% if tscript_link %}{{ translate.tscript_link|safe }}{% if admin_link %}{{ BR|default:"<br />" }}{% endif %}{% endif %}
{% if admin_link %}<a href="{% url 'admin:bots_translate_change' translate.pk %}" onclick="return popup(this, '60%', '80%', '?_popup=1')" title="Bots {% trans 'Admin translate' %} {{ translate.pk }}" class="button pad2 ico-translate" data-after="{% trans 'Admin' %}"></a>{% endif %}
{% else %}<span class="icon-no"> {{ tscript }}</span>{% endif %}
{% endwith %}{% else %}{{ tscript }}{% endif %}